version: "3.7"
services:
  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: erpnext
      MARIADB_USER: erpnext
      MARIADB_PASSWORD: erpnext
    ports:
      - 3306:3306
    volumes:
      - mariadb-erp13:/var/lib/mysql

  frappe:
    image: frappe/bench:latest
    command: sleep infinity
    volumes:
      - ..:/workspace
    working_dir: /workspace/development
    ports:
      - "8000-8005:8000-8005"
      - "9000-9005:9000-9005"

  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  redis-socketio:
    image: redis:alpine

volumes:
  mariadb-erp13:
